# block2counts - Dictionary for ICD-10 count tracking

block2counts = {
    'A00-A09 Intestinal infectious diseases': 0,
    'A15-A19 Tuberculosis': 0,
    'A20-A28 Certain zoonotic bacterial diseases': 0,
    'A30-A49 Other bacterial diseases': 0,
    'A50-A64 Infections with a predominantly sexual mode of transmission': 0,
    'A65-A69 Other spirochaetal diseases': 0,
    'A70-A74 Other diseases caused by chlamydiae': 0,
    'A75-A79 Rickettsioses': 0,
    'A80-A89 Viral infections of the central nervous system': 0,
    'A90-A99 Arthropod-borne viral fevers and viral haemorrhagic fevers': 0,
    'B00-B09 Viral infections characterized by skin and mucous membrane lesions': 0,
    'B10-B10 Other human herpesviruses': 0,
    'B15-B19 Viral hepatitis': 0,
    'B20-B24 Human immunodeficiency virus [HIV] disease': 0,
    'B25-B34 Other viral diseases': 0,
    'B35-B49 Mycoses': 0,
    'B50-B64 Protozoal diseases': 0,
    'B65-B83 Helminthiases': 0,
    'B85-B89 Pediculosis, acariasis and other infestations': 0,
    'B90-B94 Sequelae of infectious and parasitic diseases': 0,
    'B95-B98 Bacterial, viral and other infectious agents': 0,
    'B99-B99 Other infectious diseases': 0,
    'C00-C97 Malignant neoplasms': 0,
    'D00-D09 In situ neoplasms': 0,
    'D10-D36 Benign neoplasms': 0,
    'D37-D48 Neoplasms of uncertain or unknown behaviour': 0,
    'D50-D53 Nutritional anaemias': 0,
    'D55-D59 Haemolytic anaemias': 0,
    'D60-D64 Aplastic and other anaemias': 0,
    'D65-D69 Coagulation defects, purpura and other haemorrhagic conditions': 0,
    'D70-D77 Other diseases of blood and blood-forming organs': 0,
    'D80-D89 Certain disorders involving the immune mechanism': 0,
    'E00-E07 Disorders of thyroid gland': 0,
    'E08-E13 Diabetes mellitus': 0,
    'E15-E16 Other disorders of glucose regulation and pancreatic internal secretion': 0,
    'E20-E35 Disorders of other endocrine glands': 0,
    'E40-E46 Malnutrition': 0,
    'E50-E64 Other nutritional deficiencies': 0,
    'E65-E68 Obesity and other hyperalimentation': 0,
    'E70-E90 Metabolic disorders': 0,
    'F00-F09 Organic, including symptomatic, mental disorders': 0,
    'F10-F19 Mental and behavioural disorders due to psychoactive substance use': 0,
    'F20-F29 Schizophrenia, schizotypal and delusional disorders': 0,
    'F30-F39 Mood [affective] disorders': 0,
    'F40-F48 Neurotic, stress-related and somatoform disorders': 0,
    'F50-F59 Behavioural syndromes associated with physiological disturbances and physical factors': 0,
    'F60-F69 Disorders of adult personality and behaviour': 0,
    'F70-F79 Mental retardation': 0,
    'F80-F89 Disorders of psychological development': 0,
    'F90-F98 Behavioural and emotional disorders with onset usually occurring in childhood and adolescence': 0,
    'F99-F99 Unspecified mental disorder': 0,
    'G00-G09 Inflammatory diseases of the central nervous system': 0,
    'G10-G14 Systemic atrophies primarily affecting the central nervous system': 0,
    'G20-G26 Extrapyramidal and movement disorders': 0,
    'G30-G32 Other degenerative diseases of the nervous system': 0,
    'G35-G37 Demyelinating diseases of the central nervous system': 0,
    'G40-G47 Episodic and paroxysmal disorders': 0,
    'G50-G59 Nerve, nerve root and plexus disorders': 0,
    'G60-G65 Polyneuropathies and other disorders of the peripheral nervous system': 0,
    'G70-G73 Diseases of myoneural junction and muscle': 0,
    'G80-G83 Cerebral palsy and other paralytic syndromes': 0,
    'G89-G99 Other disorders of the nervous system': 0,
    'H00-H06 Disorders of eyelid, lacrimal system and orbit': 0,
    'H10-H13 Disorders of conjunctiva': 0,
    'H15-H22 Disorders of sclera, cornea, iris and ciliary body': 0,
    'H25-H28 Disorders of lens': 0,
    'H30-H36 Disorders of choroid and retina': 0,
    'H40-H42 Glaucoma': 0,
    'H43-H45 Disorders of vitreous body and globe': 0,
    'H46-H48 Disorders of optic nerve and visual pathways': 0,
    'H49-H52 Disorders of ocular muscles, binocular movement, accommodation and refraction': 0,
    'H53-H54 Visual disturbances and blindness': 0,
    'H55-H59 Other disorders of eye and adnexa': 0,
    'H60-H62 Diseases of external ear': 0,
    'H65-H75 Diseases of middle ear and mastoid': 0,
    'H80-H83 Diseases of inner ear': 0,
    'H90-H95 Other disorders of ear': 0,
    'I00-I02 Acute rheumatic fever': 0,
    'I05-I09 Chronic rheumatic heart diseases': 0,
    'I10-I16 Hypertensive diseases': 0,
    'I20-I25 Ischaemic heart diseases': 0,
    'I26-I28 Pulmonary heart disease and diseases of pulmonary circulation': 0,
    'I30-I52 Other forms of heart disease': 0,
    'I60-I69 Cerebrovascular diseases': 0,
    'I70-I79 Diseases of arteries, arterioles and capillaries': 0,
    'I80-I89 Diseases of veins, lymphatic vessels and lymph nodes, not elsewhere classified': 0,
    'I95-I99 Other and unspecified disorders of the circulatory system': 0,
    'J00-J06 Acute upper respiratory infections': 0,
    'J09-J18 Influenza and pneumonia': 0,
    'J20-J22 Other acute lower respiratory infections': 0,
    'J30-J39 Other diseases of upper respiratory tract': 0,
    'J40-J47 Chronic lower respiratory diseases': 0,
    'J60-J70 Lung diseases due to external agents': 0,
    'J80-J84 Other respiratory diseases principally affecting the interstitium': 0,
    'J85-J86 Suppurative and necrotic conditions of lower respiratory tract': 0,
    'J90-J94 Other diseases of pleura': 0,
    'J95-J99 Other diseases of the respiratory system': 0,
    'K00-K14 Diseases of oral cavity, salivary glands and jaws': 0,
    'K20-K31 Diseases of oesophagus, stomach and duodenum': 0,
    'K35-K38 Diseases of appendix': 0,
    'K40-K46 Hernia': 0,
    'K50-K52 Noninfective enteritis and colitis': 0,
    'K55-K64 Other diseases of intestines': 0,
    'K65-K68 Diseases of peritoneum and retroperitoneum': 0,
    'K70-K77 Diseases of liver': 0,
    'K80-K87 Disorders of gallbladder, biliary tract and pancreas': 0,
    'K90-K95 Other diseases of the digestive system': 0,
    'L00-L08 Infections of the skin and subcutaneous tissue': 0,
    'L10-L14 Bullous disorders': 0,
    'L20-L30 Dermatitis and eczema': 0,
    'L40-L45 Papulosquamous disorders': 0,
    'L49-L54 Urticaria and erythema': 0,
    'L50-L54 Urticaria and erythema': 0,
    'L55-L59 Radiation-related disorders of the skin and subcutaneous tissue': 0,
    'L60-L75 Disorders of skin appendages': 0,
    'L76-L76 Intraoperative and postprocedural complications of skin and subcutaneous tissue': 0,
    'L80-L99 Other disorders of the skin and subcutaneous tissue': 0,
    'M00-M25 Arthropathies': 0,
    'M26-M27 Dentofacial anomalies [including malocclusion] and other disorders of jaw': 0,
    'M30-M36 Systemic connective tissue disorders': 0,
    'M40-M54 Dorsopathies': 0,
    'M60-M79 Soft tissue disorders': 0,
    'M80-M94 Osteopathies and chondropathies': 0,
    'M95-M99 Other disorders of the musculoskeletal system and connective tissue': 0,
    'N00-N08 Glomerular diseases': 0,
    'N10-N16 Renal tubulo-interstitial diseases': 0,
    'N17-N19 Renal failure': 0,
    'N20-N23 Urolithiasis': 0,
    'N25-N29 Other disorders of kidney and ureter': 0,
    'N30-N39 Other diseases of urinary system': 0,
    'N40-N53 Diseases of male genital organs': 0,
    'N60-N65 Disorders of breast': 0,
    'N70-N77 Inflammatory diseases of female pelvic organs': 0,
    'N80-N98 Noninflammatory disorders of female genital tract': 0,
    'N99-N99 Other disorders of the genitourinary system': 0,
    'O00-O08 Pregnancy with abortive outcome': 0,
    'O09-O09 Supervision of high risk pregnancy': 0,
    'O10-O16 Oedema, proteinuria and hypertensive disorders in pregnancy, childbirth and the puerperium': 0,
    'O20-O29 Other maternal disorders predominantly related to pregnancy': 0,
    'O30-O48 Maternal care related to the fetus and amniotic cavity and possible delivery problems': 0,
    'O60-O77 Complications of labour and delivery': 0,
    'O80-O84 Delivery': 0,
    'O85-O92 Complications predominantly related to the puerperium': 0,
    'O94-O99 Other obstetric conditions, not elsewhere classified': 0,
    'P00-P04 Fetus and newborn affected by maternal factors and by complications of pregnancy, labour and delivery': 0,
    'P05-P08 Disorders related to length of gestation and fetal growth': 0,
    'P09-P09 Abnormal findings on neonatal screening': 0,
    'P10-P15 Birth trauma': 0,
    'P19-P29 Respiratory and cardiovascular disorders specific to the perinatal period': 0,
    'P35-P39 Infections specific to the perinatal period': 0,
    'P50-P61 Haemorrhagic and haematological disorders of fetus and newborn': 0,
    'P70-P74 Transitory endocrine and metabolic disorders specific to fetus and newborn': 0,
    'P75-P78 Digestive system disorders of fetus and newborn': 0,
    'P80-P83 Conditions involving the integument and temperature regulation of fetus and newborn': 0,
    'P84-P84 Other problems with newborn': 0,
    'P90-P96 Other disorders originating in the perinatal period': 0,
    'Q00-Q07 Congenital malformations of the nervous system': 0,
    'Q10-Q18 Congenital malformations of eye, ear, face and neck': 0,
    'Q20-Q28 Congenital malformations of the circulatory system': 0,
    'Q30-Q34 Congenital malformations of the respiratory system': 0,
    'Q35-Q37 Cleft lip and cleft palate': 0,
    'Q38-Q45 Other congenital malformations of the digestive system': 0,
    'Q50-Q56 Congenital malformations of genital organs': 0,
    'Q60-Q64 Congenital malformations of the urinary system': 0,
    'Q65-Q79 Congenital malformations and deformations of the musculoskeletal system': 0,
    'Q80-Q89 Other congenital malformations': 0,
    'Q90-Q99 Chromosomal abnormalities, not elsewhere classified': 0,
    'R00-R09 Symptoms and signs involving the circulatory and respiratory systems': 0,
    'R10-R19 Symptoms and signs involving the digestive system and abdomen': 0,
    'R20-R23 Symptoms and signs involving the skin and subcutaneous tissue': 0,
    'R25-R29 Symptoms and signs involving the nervous and musculoskeletal systems': 0,
    'R30-R39 Symptoms and signs involving the urinary system': 0,
    'R40-R46 Symptoms and signs involving cognition, perception, emotional state and behaviour': 0,
    'R47-R49 Symptoms and signs involving speech and voice': 0,
    'R50-R69 General symptoms and signs': 0,
    'R70-R79 Abnormal findings on examination of blood, without diagnosis': 0,
    'R80-R82 Abnormal findings on examination of urine, without diagnosis': 0,
    'R83-R89 Abnormal findings on examination of other body fluids, substances and tissues, without diagnosis': 0,
    'R90-R94 Abnormal findings on diagnostic imaging and in function studies, without diagnosis': 0,
    'R95-R99 Ill-defined and unknown causes of mortality': 0,
    'S00-S09 Injuries to the head': 0,
    'S10-S19 Injuries to the neck': 0,
    'S20-S29 Injuries to the thorax': 0,
    'S30-S39 Injuries to the abdomen, lower back, lumbar spine and pelvis': 0,
    'S40-S49 Injuries to the shoulder and upper arm': 0,
    'S50-S59 Injuries to the elbow and forearm': 0,
    'S60-S69 Injuries to the wrist and hand': 0,
    'S70-S79 Injuries to the hip and thigh': 0,
    'S80-S89 Injuries to the knee and lower leg': 0,
    'S90-S99 Injuries to the ankle and foot': 0,
    'T00-T07 Injuries involving multiple body regions': 0,
    'T08-T14 Injuries to unspecified part of trunk, limb or body region': 0,
    'T15-T19 Effects of foreign body entering through natural orifice': 0,
    'T20-T32 Burns and corrosions': 0,
    'T33-T35 Frostbite': 0,
    'T36-T50 Poisoning by drugs, medicaments and biological substances': 0,
    'T51-T65 Toxic effects of substances chiefly nonmedicinal as to source': 0,
    'T66-T78 Other and unspecified effects of external causes': 0,
    'T79-T79 Certain early complications of trauma': 0,
    'T80-T88 Complications of surgical and medical care, not elsewhere classified': 0,
    'T90-T98 Sequelae of injuries, of poisoning and of other consequences of external causes': 0,
    'U00-U49 Provisional assignment of new diseases of uncertain etiology or emergency use': 0,
    'U82-U85 Resistance to antimicrobial and antineoplastic drugs': 0,
    'V00-V09 Pedestrian injured in transport accident': 0,
    'V10-V19 Pedal cycle rider injured in transport accident': 0,
    'V20-V29 Motorcycle rider injured in transport accident': 0,
    'V30-V39 Occupant of three-wheeled motor vehicle injured in transport accident': 0,
    'V40-V49 Car occupant injured in transport accident': 0,
    'V50-V59 Occupant of pick-up truck or van injured in transport accident': 0,
    'V60-V69 Occupant of heavy transport vehicle injured in transport accident': 0,
    'V70-V79 Bus occupant injured in transport accident': 0,
    'V80-V89 Other land transport accidents': 0,
    'V90-V94 Water transport accidents': 0,
    'V95-V97 Air and space transport accidents': 0,
    'V98-V99 Other and unspecified transport accidents': 0,
    'W00-W19 Slipping, tripping, stumbling and falls': 0,
    'W20-W49 Exposure to inanimate mechanical forces': 0,
    'W50-W64 Exposure to animate mechanical forces': 0,
    'W65-W74 Accidental non-transport drowning and submersion': 0,
    'W85-W99 Exposure to electric current, radiation and extreme ambient air temperature and pressure': 0,
    'X00-X08 Exposure to smoke, fire and flames': 0,
    'X10-X19 Contact with heat and hot substances': 0,
    'X30-X39 Exposure to forces of nature': 0,
    'X50-X50 Overexertion and strenuous or repetitive movements': 0,
    'X52-X58 Accidental exposure to other specified factors': 0,
    'X60-X84 Intentional self-harm': 0,
    'X92-X99 Assault': 0,
    'Y00-Y09 Assault': 0,
    'Y10-Y34 Event of undetermined intent': 0,
    'Y35-Y38 Legal intervention, operations of war, military operations, and terrorism': 0,
    'Y40-Y84 Complications of medical and surgical care': 0,
    'Y85-Y89 Sequelae of external causes of morbidity and mortality': 0,
    'Y90-Y99 Supplementary factors related to causes of morbidity and mortality classified elsewhere': 0,
    'Z00-Z13 Persons encountering health services for examination and investigation': 0,
    'Z14-Z15 Genetic carrier and genetic susceptibility to disease': 0,
    'Z16-Z16 Resistance to antimicrobial drugs': 0,
    'Z17-Z17 Estrogen, and other hormones and factors receptor status': 0,
    'Z18-Z18 Retained foreign body fragments': 0,
    'Z19-Z19 Hormone sensitivity malignancy status': 0,
    'Z20-Z29 Persons with potential health hazards related to communicable diseases': 0,
    'Z30-Z39 Persons encountering health services in circumstances related to reproduction': 0,
    'Z40-Z54 Persons encountering health services for specific procedures and health care': 0,
    'Z55-Z65 Persons with potential health hazards related to socioeconomic and psychosocial circumstances': 0,
    'Z66-Z66 Do not resuscitate status': 0,
    'Z67-Z67 Do not intubate status': 0,
    'Z68-Z68 Do not resuscitate status': 0,
    'Z69-Z76 Persons encountering health services in other circumstances': 0,
    'Z77-Z99 Persons with potential health hazards related to family and personal history and certain conditions influencing health status': 0
}
