import __init__

import pandas as pd
import os
import json
from utils.helper_functions import get_files, load_mapping_file # Assuming helper_functions is in utils
from db.queries.post.post_bench29 import add_cases_bench_diagnosis
from db.queries.get.get_bench29 import get_cases_bench
from db.utils.db_utils import get_session


PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__),  "..", ".."))


DIR_TREATMENT = os.path.join(PROJECT_ROOT, "data", "tests", "treatment")
DIR_FINAL_TESTS = os.path.join(PROJECT_ROOT, "data", "tests", "final")

# Path to the mapping file generated by load_cases.py
# MAPPING_FILE_PATH = os.path.join(PROJECT_ROOT, "data", "tests", "mapping_file.jsonl") # Uncomment and adjust path as needed

# Exclusion lists for specific files
EXCLUDED_TREATMENT_FILES = []
EXCLUDED_FINAL_TEST_FILES = []

# Flags to exclude entire directories
EXCLUDE_ALL_TREATMENT = False
EXCLUDE_ALL_FINAL_TESTS = True # Defaulting to True as in load_cases.py

VERBOSE = False



# --- Core Logic ---

def load_golden_diagnosis(session, row, mapping_data, test_name, golden_diagnosis_column, alternative_diagnosis_column, verbose=False):
    """
    Loads a single golden diagnosis record into the database.

    Args:
        session: The database session object.
        row: A Pandas Series representing a row from the test CSV.
        mapping_data: Dictionary mapping (test_name, original_row_index) to cases_bench_id.
        test_name: The name of the test file being processed.
        golden_diagnosis_column: Name of the column containing the golden diagnosis.
        alternative_diagnosis_column: Name of the column containing the alternative diagnosis.
        verbose: Boolean flag for verbose output.
    """



    # Prepare data for add_cases_bench_diagnosis
    # Map CSV columns to function arguments
    gold_diagnosis_val = row.get(golden_diagnosis_column)
    alternative_diagnosis_val = row.get(alternative_diagnosis_column) if alternative_diagnosis_column else None

    if pd.isna(gold_diagnosis_val):
        if verbose:
            print(f"  Warning: Skipping row id {row_id_str} in {test_name} due to missing {golden_diagnosis_column}.")
        return
    row_id = row.get('id')
    cases_bench_id = int(get_cases_bench(session, hospital = test_name, source_file_path = str(  row_id), id_only = True))
    if cases_bench_id is None:
        print(f"  Warning: No matching case found in DB for {test_name}, source_file_path (row id) {row_id}. Skipping golden diagnosis.")
        return
    debug = False
    if debug:
        print(type(row_id))

        print(get_cases_bench(session, source_file_path = str(row_id), first_only = True).original_text)

        print(row)
        print(row["case"])
        print()
        input()
    # Add the golden diagnosis record
    diagnosis_id = add_cases_bench_diagnosis(
        session=session,
        case_id=cases_bench_id,
        gold_diagnosis=gold_diagnosis_val,
        alternative_diagnosis=alternative_diagnosis_val if pd.notna(alternative_diagnosis_val) else None,
        further=None, # No 'further' column identified in CSV
        verbose=verbose
    )

def load_golden_diagnosis_file(session,
full_path,
mapping_data,
golden_diagnosis_column = "golden_diagnosis",
alternative_diagnosis_column = "icd10_diagnostic_name",
 verbose=False):
    """
    Loads golden diagnoses from a single test CSV file into the database.

    Args:
        session: The database session object.
        full_path: The absolute path to the CSV file.
        mapping_data: Dictionary mapping (test_name, original_row_index) to cases_bench_id.
        verbose: Boolean flag for verbose output.
    """
    if not os.path.exists(full_path):
        print(f"Error: Test file not found at {full_path}")
        return

    df = pd.read_csv(full_path)
    # print(len(df))
    # input()
    if df.empty:
        print(f"Warning: Test file is empty at {full_path}")
        return

    file_name = os.path.basename(full_path)
    test_name = file_name.replace(".csv", "")
    print(f"Processing golden diagnoses for test: {test_name}")
    print(f"  df: {df}")

    # Define required columns for golden diagnosis
    required_columns = ['id', golden_diagnosis_column]
    if alternative_diagnosis_column and alternative_diagnosis_column in df.columns:
        required_columns.append(alternative_diagnosis_column)
    else:
        alternative_diagnosis_column = None # Ensure it's None if not present or not needed

    if not all(col in df.columns for col in required_columns if col is not None): # Check only non-None cols
        print(f"Error: Missing required columns in {full_path}. Needed: {required_columns}")
        return

    for index, row in df.iterrows():
        load_golden_diagnosis(session, row, mapping_data, test_name, golden_diagnosis_column, alternative_diagnosis_column, verbose)

def load_all_golden_diagnoses(session, all_test_files, dir_final_tests, dir_treatment=None, verbose=False):
    """
    Loads golden diagnoses from multiple specified test files into the database.

    Args:
        session: The database session object.
        all_test_files: A list of filenames (relative to their directories) to process.
        mapping_data: Dictionary mapping (test_name, index) tuples to cases_bench_id.
        dir_final_tests: The directory path for 'final' test files.
        dir_treatment: The directory path for 'treatment' test files. Optional.
        verbose: Boolean flag for verbose output.
    """
    treatment_filenames = [os.path.basename(f) for f in get_files("test_*", dir_treatment, verbose=False)] if dir_treatment else []

    for file in all_test_files:
        print(f"Processing file for golden diagnoses: {file}")
        is_treatment_file = file in treatment_filenames and dir_treatment is not None
        dir_input = dir_treatment if is_treatment_file else dir_final_tests
        # Construct the full path to the mapping file within the directory
        mapping_file_full_path = os.path.join(dir_input, "mapping_output.jsonl")
        mapping_data = load_mapping_file(mapping_file_full_path)
        if mapping_data is None:
            print(f"Error: Failed to load mapping file at {mapping_file_full_path}. Skipping file {file}.")
            continue # Skip to the next file if mapping is not found for this directory
        if not mapping_data:
            print("Warning: Mapping file loaded but is empty.")
        if not os.path.isdir(dir_input):
            print(f"Warning: Directory not found: {dir_input}. Skipping file {file}.")
            continue

        full_path = os.path.join(dir_input, file)

        if not os.path.isfile(full_path):
            print(f"Warning: File not found: {full_path}. Skipping.")
            continue

        load_golden_diagnosis_file(session, full_path, mapping_data, verbose=verbose)


def main(
        dir_treatment=DIR_TREATMENT,
        dir_final_tests=DIR_FINAL_TESTS,
        excluded_treatment=None,
        excluded_final=None,
        exclude_all_treatment=EXCLUDE_ALL_TREATMENT,
        exclude_all_final=EXCLUDE_ALL_FINAL_TESTS,
        verbose=VERBOSE
    ):
    """
    Main function to orchestrate loading golden diagnoses from CSV files into the database.
    """
    excluded_treatment_files = excluded_treatment if excluded_treatment is not None else []
    excluded_final_test_files = excluded_final if excluded_final is not None else []

    session = get_session()
    if not session:
        print("Error: Failed to get database session. Exiting.")
        return



    test_pattern = "test_*.csv"
    treatment_files = []
    if dir_treatment and not exclude_all_treatment:
        treatment_files = get_files(test_pattern, dir_treatment, verbose=verbose)
        treatment_files = [f for f in treatment_files if f not in excluded_treatment_files]

    final_test_files = []
    if dir_final_tests and not exclude_all_final:
        final_test_files = get_files(test_pattern, dir_final_tests, verbose=verbose)
        final_test_files = [f for f in final_test_files if f not in excluded_final_test_files]

    all_test_files = treatment_files + final_test_files

    if not all_test_files:
        print("No test files found or selected for processing golden diagnoses.")
        return

    print(f"Found {len(all_test_files)} test files to process for golden diagnoses.")
    load_all_golden_diagnoses(session, all_test_files, dir_final_tests, dir_treatment, verbose)

    print("Golden diagnosis loading process finished.")
    session.close()


if __name__ == "__main__":
    main(
        dir_treatment=DIR_TREATMENT,
        dir_final_tests=DIR_FINAL_TESTS,

        excluded_treatment=EXCLUDED_TREATMENT_FILES,
        excluded_final=EXCLUDED_FINAL_TEST_FILES,
        exclude_all_treatment=EXCLUDE_ALL_TREATMENT,
        exclude_all_final=EXCLUDE_ALL_FINAL_TESTS,
        verbose=VERBOSE
    )