// dxGPT Complete Architecture Visualization Data
// Generated by Graph29 Sequential Prompts Framework

var nodes = [
  {
    "id": 1,
    "label": "run_dxGPT_async.py<br/>(Command-line entry)",
    "color": "#afa",
    "borderWidth": 2,
    "borderColor": "#3a3",
    "font": {
      "size": 10
    }
  },
  {
    "id": 2,
    "label": "dxGPT_async.py<br/>(Main async workflow)",
    "color": "#afa",
    "borderWidth": 2,
    "borderColor": "#3a3",
    "font": {
      "size": 10
    }
  },
  {
    "id": 3,
    "label": "set_settings()",
    "color": "#7d7",
    "borderWidth": 2,
    "borderColor": "#3a3",
    "font": {
      "size": 10
    }
  },
  {
    "id": 4,
    "label": "retrieve_and_make_prompts()",
    "color": "#7d7",
    "borderWidth": 2,
    "borderColor": "#3a3",
    "font": {
      "size": 10
    }
  },
  {
    "id": 5,
    "label": "process_results()",
    "color": "#7d7",
    "borderWidth": 2,
    "borderColor": "#3a3",
    "font": {
      "size": 10
    }
  },
  {
    "id": 6,
    "label": "1. inits configuration",
    "color": "#f9f9f9",
    "borderWidth": 2,
    "borderColor": "#999",
    "font": {
      "size": 10
    }
  },
  {
    "id": 7,
    "label": "--model_alias",
    "color": "#ffd",
    "borderWidth": 2,
    "borderColor": "#aa3",
    "font": {
      "size": 10
    }
  },
  {
    "id": 8,
    "label": "--prompt_alias",
    "color": "#ffd",
    "borderWidth": 2,
    "borderColor": "#aa3",
    "font": {
      "size": 10
    }
  },
  {
    "id": 9,
    "label": "List of Clinical Cases<br/>(Pydantic models)",
    "color": "#f9f9f9",
    "borderWidth": 2,
    "borderColor": "#999",
    "font": {
      "size": 10
    }
  },
  {
    "id": 10,
    "label": "process_all_batches()",
    "color": "#bbf",
    "borderWidth": 2,
    "borderColor": "#33f",
    "font": {
      "size": 10
    }
  },
  {
    "id": 11,
    "label": "prompts/dxGPT_prompts.py",
    "color": "#afa",
    "borderWidth": 2,
    "borderColor": "#3a3",
    "font": {
      "size": 10
    }
  },
  {
    "id": 12,
    "label": "Selected dxGPT Prompt<br/>(e.g., StandardDxGPTPrompt)",
    "color": "#ffb",
    "borderWidth": 2,
    "borderColor": "#b90",
    "font": {
      "size": 10
    }
  },
  {
    "id": 13,
    "label": "PromptBuilder",
    "color": "#bbf",
    "borderWidth": 2,
    "borderColor": "#33f",
    "font": {
      "size": 10
    }
  },
  {
    "id": 14,
    "label": "AsyncModelHandler",
    "color": "#bbf",
    "borderWidth": 2,
    "borderColor": "#33f",
    "font": {
      "size": 10
    }
  },
  {
    "id": 15,
    "label": "models/dxGPT_models.py",
    "color": "#afa",
    "borderWidth": 2,
    "borderColor": "#3a3",
    "font": {
      "size": 10
    }
  },
  {
    "id": 16,
    "label": "Selected dxGPT Model<br/>(e.g., LlamaThreeEightBConfig)",
    "color": "#ffb",
    "borderWidth": 2,
    "borderColor": "#b90",
    "font": {
      "size": 10
    }
  },
  {
    "id": 17,
    "label": "List of LLM responses<br/>(plain text)",
    "color": "#f9f9f9",
    "borderWidth": 2,
    "borderColor": "#999",
    "font": {
      "size": 10
    }
  },
  {
    "id": 18,
    "label": "--batch_size<br/>--rpm_limit<br/>--min_batch_interval",
    "color": "#ffd",
    "borderWidth": 2,
    "borderColor": "#aa3",
    "font": {
      "size": 10
    }
  },
  {
    "id": 19,
    "label": "--hospital<br/>--num_samples<br/>--verbose",
    "color": "#ffd",
    "borderWidth": 2,
    "borderColor": "#aa3",
    "font": {
      "size": 10
    }
  },
  {
    "id": 20,
    "label": "get_cases_bench()",
    "color": "#fbb",
    "borderWidth": 2,
    "borderColor": "#d33",
    "font": {
      "size": 10
    }
  },
  {
    "id": 21,
    "label": "insert_or_fetch_model()<br/>insert_or_fetch_prompt()",
    "color": "#fbb",
    "borderWidth": 2,
    "borderColor": "#d33",
    "font": {
      "size": 10
    }
  },
  {
    "id": 22,
    "label": "Models<br/>(LLM configs)",
    "color": "#f9f",
    "borderWidth": 2,
    "borderColor": "#333",
    "font": {
      "size": 10
    }
  },
  {
    "id": 23,
    "label": "Prompts<br/>(Templates)",
    "color": "#f9f",
    "borderWidth": 2,
    "borderColor": "#333",
    "font": {
      "size": 10
    }
  },
  {
    "id": 24,
    "label": "model_id",
    "color": "#f9f9f9",
    "borderWidth": 2,
    "borderColor": "#999",
    "font": {
      "size": 10
    }
  },
  {
    "id": 25,
    "label": "prompt_id",
    "color": "#f9f9f9",
    "borderWidth": 2,
    "borderColor": "#999",
    "font": {
      "size": 10
    }
  },
  {
    "id": 26,
    "label": "CasesBench<br/>(Input cases)",
    "color": "#f9f",
    "borderWidth": 2,
    "borderColor": "#333",
    "font": {
      "size": 10
    }
  },
  {
    "id": 27,
    "label": "case_bench_id",
    "color": "#f9f9f9",
    "borderWidth": 2,
    "borderColor": "#999",
    "font": {
      "size": 10
    }
  },
  {
    "id": 28,
    "label": "case_text",
    "color": "#f9f9f9",
    "borderWidth": 2,
    "borderColor": "#999",
    "font": {
      "size": 10
    }
  },
  {
    "id": 29,
    "label": "Case Model<br/>(Pydantic Schema)",
    "color": "#f9f9f9",
    "borderWidth": 2,
    "borderColor": "#999",
    "font": {
      "size": 10
    }
  },
  {
    "id": 30,
    "label": "serialization/dxgpt_pydantic_models.py",
    "color": "#afa",
    "borderWidth": 2,
    "borderColor": "#3a3",
    "font": {
      "size": 10
    }
  },
  {
    "id": 31,
    "label": "parsers/dxGPT_parsers.py",
    "color": "#afa",
    "borderWidth": 2,
    "borderColor": "#3a3",
    "font": {
      "size": 10
    }
  },
  {
    "id": 32,
    "label": "Differential Diagnosis Parser<br/>(e.g., parse_top5_xml)",
    "color": "#ffb",
    "borderWidth": 2,
    "borderColor": "#b90",
    "font": {
      "size": 10
    }
  },
  {
    "id": 33,
    "label": "Rank Parser<br/>(e.g., universal_dif_diagnosis_parser)",
    "color": "#ffb",
    "borderWidth": 2,
    "borderColor": "#b90",
    "font": {
      "size": 10
    }
  },
  {
    "id": 34,
    "label": "Raw Differential Diagnosis<br/>(Extracted text block)",
    "color": "#f9f9f9",
    "borderWidth": 2,
    "borderColor": "#999",
    "font": {
      "size": 10
    }
  },
  {
    "id": 35,
    "label": "List of Clinical Cases w/ DDx<br/>(Pydantic Models)",
    "color": "#f9f9f9",
    "borderWidth": 2,
    "borderColor": "#999",
    "font": {
      "size": 10
    }
  },
  {
    "id": 36,
    "label": "add_batch_differential_diagnoses()<br/>in dxGPT_queries",
    "color": "#fbb",
    "borderWidth": 2,
    "borderColor": "#d33",
    "font": {
      "size": 10
    }
  },
  {
    "id": 37,
    "label": "List of Clinical Cases w/ DDx and Ranks<br/>(Pydantic Models)",
    "color": "#f9f9f9",
    "borderWidth": 2,
    "borderColor": "#999",
    "font": {
      "size": 10
    }
  },
  {
    "id": 38,
    "label": "Rank Position<br/>(Integer)",
    "color": "#f9f9f9",
    "borderWidth": 2,
    "borderColor": "#999",
    "font": {
      "size": 10
    }
  },
  {
    "id": 39,
    "label": "Disease Name<br/>(String)",
    "color": "#f9f9f9",
    "borderWidth": 2,
    "borderColor": "#999",
    "font": {
      "size": 10
    }
  },
  {
    "id": 40,
    "label": "Reasoning<br/>(String)",
    "color": "#f9f9f9",
    "borderWidth": 2,
    "borderColor": "#999",
    "font": {
      "size": 10
    }
  },
  {
    "id": 41,
    "label": "queries/dxGPT_queries.py<br/>(Database operations)",
    "color": "#afa",
    "borderWidth": 2,
    "borderColor": "#3a3",
    "font": {
      "size": 10
    }
  },
  {
    "id": 42,
    "label": "add_differential_diagnosis_to_rank()<br/>in post_bench29",
    "color": "#fbb",
    "borderWidth": 2,
    "borderColor": "#d33",
    "font": {
      "size": 10
    }
  },
  {
    "id": 43,
    "label": "Differential Diagnosis ID",
    "color": "#f9f9f9",
    "borderWidth": 2,
    "borderColor": "#999",
    "font": {
      "size": 10
    }
  },
  {
    "id": 44,
    "label": "LlmDifferentialDiagnosis<br/>(Raw responses)",
    "color": "#f9f",
    "borderWidth": 2,
    "borderColor": "#333",
    "font": {
      "size": 10
    }
  },
  {
    "id": 45,
    "label": "DifferentialDiagnosis2Rank<br/>(Structured diagnoses)",
    "color": "#f9f",
    "borderWidth": 2,
    "borderColor": "#333",
    "font": {
      "size": 10
    }
  }
];

var edges = [
  {
    "id": 1,
    "from": 1,
    "to": 2,
    "label": "calls",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 2,
    "from": 2,
    "to": 3,
    "label": "calls",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 3,
    "from": 2,
    "to": 4,
    "label": "calls",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 4,
    "from": 2,
    "to": 5,
    "label": "calls",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 5,
    "from": 3,
    "to": 6,
    "label": "produces",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 6,
    "from": 6,
    "to": 7,
    "label": "produces",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 7,
    "from": 6,
    "to": 8,
    "label": "produces",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 8,
    "from": 9,
    "to": 10,
    "label": "sent to",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 9,
    "from": 8,
    "to": 11,
    "label": "sent to",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 10,
    "from": 11,
    "to": 12,
    "label": "loads",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 11,
    "from": 13,
    "to": 12,
    "label": "extends",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 12,
    "from": 12,
    "to": 10,
    "label": "used by",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 13,
    "from": 7,
    "to": 10,
    "label": "sent to",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 14,
    "from": 14,
    "to": 15,
    "label": "selects",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 15,
    "from": 15,
    "to": 16,
    "label": "loads",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 16,
    "from": 16,
    "to": 17,
    "label": "produces",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 17,
    "from": 18,
    "to": 10,
    "label": "configures",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 18,
    "from": 4,
    "to": 19,
    "label": "uses",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 19,
    "from": 19,
    "to": 20,
    "label": "sent to",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 20,
    "from": 7,
    "to": 21,
    "label": "sent to",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 21,
    "from": 8,
    "to": 21,
    "label": "sent to",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 22,
    "from": 21,
    "to": 22,
    "label": "queries",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 23,
    "from": 21,
    "to": 23,
    "label": "queries",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 24,
    "from": 22,
    "to": 24,
    "label": "returns",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 25,
    "from": 23,
    "to": 25,
    "label": "returns",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 26,
    "from": 26,
    "to": 27,
    "label": "returns",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 27,
    "from": 26,
    "to": 28,
    "label": "returns",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 28,
    "from": 27,
    "to": 29,
    "label": "part of",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 29,
    "from": 28,
    "to": 29,
    "label": "part of",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 30,
    "from": 24,
    "to": 29,
    "label": "part of",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 31,
    "from": 25,
    "to": 29,
    "label": "part of",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 32,
    "from": 29,
    "to": 9,
    "label": "generates",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 33,
    "from": 20,
    "to": 26,
    "label": "queries",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 34,
    "from": 30,
    "to": 29,
    "label": "stored in",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 35,
    "from": 10,
    "to": 14,
    "label": "calls",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 36,
    "from": 5,
    "to": 31,
    "label": "uses",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 37,
    "from": 31,
    "to": 32,
    "label": "contains",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 38,
    "from": 31,
    "to": 33,
    "label": "contains",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 39,
    "from": 17,
    "to": 32,
    "label": "passed to",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 40,
    "from": 32,
    "to": 34,
    "label": "produces",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 41,
    "from": 34,
    "to": 33,
    "label": "input for",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 42,
    "from": 9,
    "to": 35,
    "label": "augmented to",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 43,
    "from": 34,
    "to": 35,
    "label": "stored as",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 44,
    "from": 35,
    "to": 36,
    "label": "sent to DB via",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 45,
    "from": 35,
    "to": 37,
    "label": "augmented to",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 46,
    "from": 33,
    "to": 38,
    "label": "extracts",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 47,
    "from": 33,
    "to": 39,
    "label": "extracts",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 48,
    "from": 33,
    "to": 40,
    "label": "extracts",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 49,
    "from": 2,
    "to": 41,
    "label": "uses",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 50,
    "from": 41,
    "to": 36,
    "label": "calls",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 51,
    "from": 41,
    "to": 42,
    "label": "contains",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 52,
    "from": 36,
    "to": 43,
    "label": "generates",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 53,
    "from": 36,
    "to": 44,
    "label": "writes to",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 54,
    "from": 38,
    "to": 37,
    "label": "stored in",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 55,
    "from": 39,
    "to": 37,
    "label": "stored in",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 56,
    "from": 40,
    "to": 37,
    "label": "stored in",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 57,
    "from": 43,
    "to": 37,
    "label": "stored in",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 58,
    "from": 37,
    "to": 42,
    "label": "sent to DB via",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 59,
    "from": 42,
    "to": 45,
    "label": "writes to",
    "arrows": "to",
    "font": {
      "size": 8
    }
  }
];
