// Judge Severity Async Complete Architecture Visualization Data
// Generated by Graph29 Sequential Prompts Framework

var nodes = [
  {
    "id": 1,
    "label": "run_judge_severity_async.py<br/>(Command-line entry)",
    "color": "#afa",
    "borderWidth": 2,
    "borderColor": "#3a3",
    "font": {
      "size": 10
    }
  },
  {
    "id": 2,
    "label": "judge_severity_async.py<br/>(Main async workflow)",
    "color": "#afa",
    "borderWidth": 2,
    "borderColor": "#3a3",
    "font": {
      "size": 10
    }
  },
  {
    "id": 3,
    "label": "set_settings()",
    "color": "#7d7",
    "borderWidth": 2,
    "borderColor": "#3a3",
    "font": {
      "size": 10
    }
  },
  {
    "id": 4,
    "label": "retrieve_and_make_prompts()",
    "color": "#7d7",
    "borderWidth": 2,
    "borderColor": "#3a3",
    "font": {
      "size": 10
    }
  },
  {
    "id": 5,
    "label": "process_results()",
    "color": "#7d7",
    "borderWidth": 2,
    "borderColor": "#3a3",
    "font": {
      "size": 10
    }
  },
  {
    "id": 6,
    "label": "1. inits configuration",
    "color": "#f9f9f9",
    "borderWidth": 2,
    "borderColor": "#999",
    "font": {
      "size": 10
    }
  },
  {
    "id": 7,
    "label": "--model_alias",
    "color": "#ffd",
    "borderWidth": 2,
    "borderColor": "#aa3",
    "font": {
      "size": 10
    }
  },
  {
    "id": 8,
    "label": "--prompt_alias",
    "color": "#ffd",
    "borderWidth": 2,
    "borderColor": "#aa3",
    "font": {
      "size": 10
    }
  },
  {
    "id": 9,
    "label": "(Judgment Cases Pydantic Schema)",
    "color": "#f9f9f9",
    "borderWidth": 2,
    "borderColor": "#999",
    "font": {
      "size": 10
    }
  },
  {
    "id": 10,
    "label": "process_all_batches()",
    "color": "#bbf",
    "borderWidth": 2,
    "borderColor": "#33f",
    "font": {
      "size": 10
    }
  },
  {
    "id": 11,
    "label": "prompts/judge_severity_prompts.py",
    "color": "#afa",
    "borderWidth": 2,
    "borderColor": "#3a3",
    "font": {
      "size": 10
    }
  },
  {
    "id": 12,
    "label": "Selected Severity Judge Prompt<br/>(e.g., StandardSeverityJudgePrompt)",
    "color": "#ffb",
    "borderWidth": 2,
    "borderColor": "#b90",
    "font": {
      "size": 10
    }
  },
  {
    "id": 13,
    "label": "PromptBuilder",
    "color": "#bbf",
    "borderWidth": 2,
    "borderColor": "#33f",
    "font": {
      "size": 10
    }
  },
  {
    "id": 14,
    "label": "AsyncModelHandler",
    "color": "#bbf",
    "borderWidth": 2,
    "borderColor": "#33f",
    "font": {
      "size": 10
    }
  },
  {
    "id": 15,
    "label": "models/judge_severity_models.py",
    "color": "#afa",
    "borderWidth": 2,
    "borderColor": "#3a3",
    "font": {
      "size": 10
    }
  },
  {
    "id": 16,
    "label": "Selected Severity Judge Model<br/>(e.g., LlamaThreeEightBConfig)",
    "color": "#ffb",
    "borderWidth": 2,
    "borderColor": "#b90",
    "font": {
      "size": 10
    }
  },
  {
    "id": 17,
    "label": "List of Severity Assessments<br/>(plain text)",
    "color": "#f9f9f9",
    "borderWidth": 2,
    "borderColor": "#999",
    "font": {
      "size": 10
    }
  },
  {
    "id": 18,
    "label": "--batch_size<br/>--rpm_limit<br/>--min_batch_interval",
    "color": "#ffd",
    "borderWidth": 2,
    "borderColor": "#aa3",
    "font": {
      "size": 10
    }
  },
  {
    "id": 19,
    "label": "--differential_diagnosis_model<br/>--test_name<br/>--max_diagnoses",
    "color": "#ffd",
    "borderWidth": 2,
    "borderColor": "#aa3",
    "font": {
      "size": 10
    }
  },
  {
    "id": 20,
    "label": "get_cases()<br/>get_case_to_golden_diagnosis_mapping()<br/>get_model_names_from_differential_diagnosis()<br/>get_ranks_for_hospital_and_model_id()<br/>get_model_id_from_name()<br/>create_nested_diagnosis_dict()",
    "color": "#fbb",
    "borderWidth": 2,
    "borderColor": "#d33",
    "font": {
      "size": 10
    }
  },
  {
    "id": 21,
    "label": "insert_or_fetch_model()<br/>insert_or_fetch_prompt()",
    "color": "#fbb",
    "borderWidth": 2,
    "borderColor": "#d33",
    "font": {
      "size": 10
    }
  },
  {
    "id": 22,
    "label": "Models<br/>(LLM configs)",
    "color": "#f9f",
    "borderWidth": 2,
    "borderColor": "#333",
    "font": {
      "size": 10
    }
  },
  {
    "id": 23,
    "label": "Prompts<br/>(Templates)",
    "color": "#f9f",
    "borderWidth": 2,
    "borderColor": "#333",
    "font": {
      "size": 10
    }
  },
  {
    "id": 24,
    "label": "model_id",
    "color": "#f9f9f9",
    "borderWidth": 2,
    "borderColor": "#999",
    "font": {
      "size": 10
    }
  },
  {
    "id": 25,
    "label": "prompt_id",
    "color": "#f9f9f9",
    "borderWidth": 2,
    "borderColor": "#999",
    "font": {
      "size": 10
    }
  },
  {
    "id": 26,
    "label": "CasesBench<br/>(Input cases)",
    "color": "#f9f",
    "borderWidth": 2,
    "borderColor": "#333",
    "font": {
      "size": 10
    }
  },
  {
    "id": 27,
    "label": "case_bench_id",
    "color": "#f9f9f9",
    "borderWidth": 2,
    "borderColor": "#999",
    "font": {
      "size": 10
    }
  },
  {
    "id": 28,
    "label": "case_text",
    "color": "#f9f9f9",
    "borderWidth": 2,
    "borderColor": "#999",
    "font": {
      "size": 10
    }
  },
  {
    "id": 29,
    "label": "Case Model<br/>(Pydantic Schema)",
    "color": "#f9f9f9",
    "borderWidth": 2,
    "borderColor": "#999",
    "font": {
      "size": 10
    }
  },
  {
    "id": 30,
    "label": "List of Clinical Cases<br/>(Pydantic models)",
    "color": "#f9f9f9",
    "borderWidth": 2,
    "borderColor": "#999",
    "font": {
      "size": 10
    }
  },
  {
    "id": 31,
    "label": "GoldenDiagnoses<br/>(Ground truth)",
    "color": "#f9f",
    "borderWidth": 2,
    "borderColor": "#333",
    "font": {
      "size": 10
    }
  },
  {
    "id": 32,
    "label": "DifferentialDiagnosis2Rank<br/>(Ranked diagnoses)",
    "color": "#f9f",
    "borderWidth": 2,
    "borderColor": "#333",
    "font": {
      "size": 10
    }
  },
  {
    "id": 33,
    "label": "serialization/judge_severity_pydantic_models.py",
    "color": "#afa",
    "borderWidth": 2,
    "borderColor": "#3a3",
    "font": {
      "size": 10
    }
  },
  {
    "id": 34,
    "label": "parsers/judge_severity_parser.py",
    "color": "#afa",
    "borderWidth": 2,
    "borderColor": "#3a3",
    "font": {
      "size": 10
    }
  },
  {
    "id": 35,
    "label": "Severity Assessment Parser<br/>(e.g., parse_judged_severity)",
    "color": "#ffb",
    "borderWidth": 2,
    "borderColor": "#b90",
    "font": {
      "size": 10
    }
  },
  {
    "id": 36,
    "label": "Raw Severity Assessment<br/>(JSON response)",
    "color": "#f9f9f9",
    "borderWidth": 2,
    "borderColor": "#999",
    "font": {
      "size": 10
    }
  },
  {
    "id": 37,
    "label": "List of Judgment Cases w/ Severity Results<br/>(Pydantic Models)",
    "color": "#f9f9f9",
    "borderWidth": 2,
    "borderColor": "#999",
    "font": {
      "size": 10
    }
  },
  {
    "id": 38,
    "label": "add_severity_results_to_db()<br/>in severity_queries",
    "color": "#fbb",
    "borderWidth": 2,
    "borderColor": "#d33",
    "font": {
      "size": 10
    }
  },
  {
    "id": 39,
    "label": "differential_diagnosis_severity_assessment_id<br/>(Integer)",
    "color": "#f9f9f9",
    "borderWidth": 2,
    "borderColor": "#999",
    "font": {
      "size": 10
    }
  },
  {
    "id": 40,
    "label": "cases_bench_id<br/>(Integer)",
    "color": "#f9f9f9",
    "borderWidth": 2,
    "borderColor": "#999",
    "font": {
      "size": 10
    }
  },
  {
    "id": 41,
    "label": "rank_id<br/>(Integer)",
    "color": "#f9f9f9",
    "borderWidth": 2,
    "borderColor": "#999",
    "font": {
      "size": 10
    }
  },
  {
    "id": 42,
    "label": "queries/severity_queries.py<br/>(Database operations)",
    "color": "#afa",
    "borderWidth": 2,
    "borderColor": "#3a3",
    "font": {
      "size": 10
    }
  },
  {
    "id": 43,
    "label": "DifferentialDiagnosis2SeverityAssessment<br/>(Severity assessments)",
    "color": "#f9f",
    "borderWidth": 2,
    "borderColor": "#333",
    "font": {
      "size": 10
    }
  }
];

var edges = [
  {
    "id": 1,
    "from": 1,
    "to": 2,
    "label": "calls",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 2,
    "from": 2,
    "to": 3,
    "label": "calls",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 3,
    "from": 2,
    "to": 4,
    "label": "calls",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 4,
    "from": 2,
    "to": 5,
    "label": "calls",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 5,
    "from": 3,
    "to": 6,
    "label": "produces",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 6,
    "from": 6,
    "to": 7,
    "label": "produces",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 7,
    "from": 6,
    "to": 8,
    "label": "produces",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 8,
    "from": 9,
    "to": 10,
    "label": "sent to",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 9,
    "from": 8,
    "to": 11,
    "label": "sent to",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 10,
    "from": 11,
    "to": 12,
    "label": "loads",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 11,
    "from": 13,
    "to": 12,
    "label": "extends",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 12,
    "from": 12,
    "to": 10,
    "label": "used by",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 13,
    "from": 7,
    "to": 10,
    "label": "sent to",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 14,
    "from": 14,
    "to": 15,
    "label": "selects",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 15,
    "from": 15,
    "to": 16,
    "label": "loads",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 16,
    "from": 16,
    "to": 17,
    "label": "produces",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 17,
    "from": 18,
    "to": 10,
    "label": "configures",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 18,
    "from": 4,
    "to": 19,
    "label": "uses",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 19,
    "from": 19,
    "to": 20,
    "label": "sent to",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 20,
    "from": 7,
    "to": 21,
    "label": "sent to",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 21,
    "from": 8,
    "to": 21,
    "label": "sent to",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 22,
    "from": 21,
    "to": 22,
    "label": "queries",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 23,
    "from": 21,
    "to": 23,
    "label": "queries",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 24,
    "from": 22,
    "to": 24,
    "label": "returns",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 25,
    "from": 23,
    "to": 25,
    "label": "returns",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 26,
    "from": 26,
    "to": 27,
    "label": "returns",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 27,
    "from": 26,
    "to": 28,
    "label": "returns",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 28,
    "from": 27,
    "to": 29,
    "label": "part of",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 29,
    "from": 28,
    "to": 29,
    "label": "part of",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 30,
    "from": 24,
    "to": 29,
    "label": "part of",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 31,
    "from": 25,
    "to": 29,
    "label": "part of",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 32,
    "from": 29,
    "to": 30,
    "label": "generates",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 33,
    "from": 20,
    "to": 26,
    "label": "queries",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 34,
    "from": 20,
    "to": 31,
    "label": "queries",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 35,
    "from": 20,
    "to": 32,
    "label": "queries",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 36,
    "from": 33,
    "to": 29,
    "label": "stored in",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 37,
    "from": 29,
    "to": 9,
    "label": "generates",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 38,
    "from": 10,
    "to": 14,
    "label": "calls",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 39,
    "from": 5,
    "to": 34,
    "label": "uses",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 40,
    "from": 34,
    "to": 35,
    "label": "contains",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 41,
    "from": 17,
    "to": 35,
    "label": "passed to",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 42,
    "from": 35,
    "to": 36,
    "label": "produces",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 43,
    "from": 30,
    "to": 37,
    "label": "augmented to",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 44,
    "from": 36,
    "to": 37,
    "label": "stored as",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 45,
    "from": 37,
    "to": 38,
    "label": "sent to DB via",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 46,
    "from": 35,
    "to": 39,
    "label": "extracts",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 47,
    "from": 35,
    "to": 40,
    "label": "extracts",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 48,
    "from": 35,
    "to": 41,
    "label": "extracts",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 49,
    "from": 2,
    "to": 42,
    "label": "uses",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 50,
    "from": 42,
    "to": 38,
    "label": "calls",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 51,
    "from": 38,
    "to": 43,
    "label": "writes to",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 52,
    "from": 39,
    "to": 37,
    "label": "stored in",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 53,
    "from": 40,
    "to": 37,
    "label": "stored in",
    "arrows": "to",
    "font": {
      "size": 8
    }
  },
  {
    "id": 54,
    "from": 41,
    "to": 37,
    "label": "stored in",
    "arrows": "to",
    "font": {
      "size": 8
    }
  }
];
